import type { LectureDeck } from "./types";

const source = { label: "Lecture 4 · Extraction, filtering, and auditing" };
const example = { label: "Constructed example · Lecture 4" };
const pdfDocs = { label: "PyMuPDF docs · layout-specific teaching fixture", url: "https://pymupdf.readthedocs.io/en/latest/recipes-text.html" };
const deck: LectureDeck = {
  number: 4,
  title: "Document extraction, quality filtering, and corpus auditing",
  subtitle: "The page looked clean. The equation disappeared.",
  textAnchor: "lecture-4-introduction",
  outlineTextAnchor: "lecture-4-outline",
  parts: [
    {
      id: "recover-the-document",
      label: "Part I",
      title: "Recover and evaluate the document",
      startAt: "More text—or more of the wrong text?",
      topics: ["Output contract", "Format-specific extraction", "Reference evaluation"],
      notes: "Start with the acquired objects and decide what each training document should contain. Establish a common output contract, follow the extraction paths for different formats, and test whether the resulting documents preserve the intended content.",
    },
    {
      id: "normalize-and-identify-language",
      label: "Part II",
      title: "Normalize text and identify language",
      startAt: "Same word, new encoding—or new wording?",
      topics: ["Unicode preservation", "Language evidence", "Mixed-language errors"],
      notes: "Once extraction has recovered the content and its structure, turn to text representation and language. Normalization and language identification need explicit policies and measured error rates, especially for multilingual and mixed-language material.",
    },
    {
      id: "decide-what-to-keep",
      label: "Part III",
      title: "Define quality and decide what to keep",
      startAt: "Which property is called quality?",
      topics: ["Quality rubric", "Retained and rejected audits", "Threshold decisions"],
      notes: "With candidate documents in hand, define what makes them useful for the intended training objective. Connect quality signals to human labels, measure errors on both sides of a filter, and turn those measurements into a defensible retention policy.",
    },
    {
      id: "audit-corpus-changes",
      label: "Part IV",
      title: "Audit how processing changes the corpus",
      startAt: "Document retention by source",
      topics: ["Before and after", "Coverage and weighting", "Contextual inspection"],
      notes: "A filter makes decisions about individual documents, but its accumulated effects change the corpus. Track which sources and languages survive, then inspect the text behind suspicious statistics to investigate shifts in coverage.",
    },
    {
      id: "assemble-and-test-the-pipeline",
      label: "Part V",
      title: "Assemble, test, and defend the pipeline",
      startAt: "Reject obvious failures before costly scoring",
      topics: ["Stage order and cost", "End-to-end trace", "Evidence and limits"],
      notes: "Bring the decisions together in an executable, auditable process. Compare stage order and cost, follow one document through the full pipeline, and distinguish a successful corpus audit from evidence of downstream model improvement. The extended policy-comparison checkpoint remains reading rather than an in-class activity.",
    },
  ],
  slides: [
    {
      title: "More text—or more of the wrong text?",
      textAnchor: "extraction-length-question",
      section: "1. Define the output contract before choosing an extractor",
      kind: "question",
      prompt: "Two extractors return 7,500 and 5,000 characters.\nWhich recovered the better document?",
      answer: "Length alone cannot distinguish article text from menus.",
      notes: "Open with the chapter's length comparison and collect a few proposed criteria before revealing the answer. A larger output can contain additional teaching content or additional boilerplate; the document contract decides which.",
      source: example,
    },
    {
      title: "Three formats, one output contract",
      textAnchor: "running-corpus-example",
      section: "Running example: processing the Armenian technical corpus",
      kind: "table",
      headers: ["Input", "Extraction path", "Output"],
      rows: [["HTML", "Select main-content blocks", "Ordered blocks"], ["PDF", "Text layer / OCR + layout", "Ordered blocks"], ["Structured row", "Map named fields", "Ordered blocks"]],
      notes: "Use the chapter's Armenian technical corpus as one illustrative multilingual case, not as a required course project. Its HTML, PDF, and translated-record branches motivate a common schema without requiring the same parser for every source.",
      source,
    },
    {
      title: "Natural Armenian: article, not site chrome",
      textAnchor: "natural-armenian-specimen",
      section: "Three source families, three concrete inputs",
      kind: "specimen",
      specimens: [
        { label: "HTML capture", text: "<nav>Գլխավոր | Մշակույթ</nav>\n<article>\n <h1>Քաղաքը առավոտյան</h1>\n <p>Երևանի փողոցները վաղ\n առավոտյան խաղաղ են։</p>\n</article>\n<footer>Գովազդ</footer>" },
        { label: "Retained document", text: "[heading]\nՔաղաքը առավոտյան\n\n[paragraph]\nԵրևանի փողոցները վաղ\nառավոտյան խաղաղ են։" },
      ],
      notes: "This is a constructed Armenian news-page fixture, not a quotation from Yerevan City Magazine. Select the article's heading and paragraph, exclude site navigation and advertising, and preserve the acquired-object identity in the audit record.",
      source: example,
    },
    {
      title: "Scientific text: keep the referenced equation",
      textAnchor: "educational-armenian-specimen",
      section: "Three source families, three concrete inputs",
      kind: "specimen",
      specimens: [
        { label: "HTML or positioned PDF blocks", text: "Նյուտոնի երկրորդ օրենքը\n\nՀաստատուն զանգվածի դեպքում\nուժը տրվում է (1) բանաձևով։\n\n[eq-1] F = ma" },
        { label: "Structured document", text: "heading: Նյուտոնի երկրորդ օրենքը\nparagraph: Հաստատուն զանգվածի\nդեպքում ուժը տրվում է (1)\nբանաձևով։\nequation: F = ma\nreference: paragraph → eq-1" },
      ],
      notes: "The semantic output is the same whether the input came from an HTML equation node or a PDF region, but source locators differ. A plain-text extractor that keeps the paragraph and loses the formula has not preserved this explanation.",
      source: example,
    },
    {
      title: "Translated STEM: map fields, retain ancestry",
      textAnchor: "translated-stem-specimen",
      section: "Three source families, three concrete inputs",
      kind: "specimen",
      specimens: [
        { label: "Structured row", text: "source_id: algebra:fixture-17\nquestion_en: Solve 3x + 5 = 20.\nquestion_hy:\n Լուծեք 3x + 5 = 20\n հավասարումը։\nsolution_hy:\n 3x = 15, հետևաբար x = 5։" },
        { label: "Training view + audit identity", text: "[question]\nԼուծեք 3x + 5 = 20 հավասարումը։\n[answer]\n3x = 15, հետևաբար x = 5։\n\norigin: translated\nfamily: algebra:fixture-17" },
      ],
      notes: "This is a constructed translated algebra record, not a row claimed to come from a named dataset. Map the Armenian fields into typed blocks, retain the English original for audit, and keep the source family so translations cannot evade ancestry-based checks.",
      source: example,
    },
    {
      title: "Branch for extraction; share justified work",
      textAnchor: "modular-extraction-pipeline",
      section: "Source adapters and shared transformations",
      kind: "flow",
      items: ["DOM / PDF / row adapters", "Typed blocks + locators", "Shared schema checks", "Block-aware normalization"],
      notes: "Modular stages expose intermediate failures and allow selective reruns. An integrated extractor can be wrapped as one adapter; share schema checks and validated transformations, but do not apply a prose whitespace or number policy indiscriminately to code and formulas.",
      source,
    },
    {
      title: "Define the document before extracting it",
      textAnchor: "document-unit",
      section: "1.1 The document unit is a modeling decision",
      kind: "comparison",
      headers: ["Possible unit", "What changes?"],
      rows: [["Thread / message", "Context and short-text statistics"], ["Book / chapter", "Length and family boundaries"], ["Repository / file", "Code boundaries and provenance"], ["Question / answer pair", "Which fields become training text"]],
      notes: "Ask students to choose a unit for one source they actually expect to process. The choice changes filtering statistics, duplicate relations, and later split boundaries, so it belongs in the specification rather than an incidental parser default.",
      source,
    },
    {
      title: "A subreddit contains threads—not one document",
      textAnchor: "forum-document-example",
      section: "1.1 The document unit is a modeling decision",
      kind: "image",
      image: { src: "lecture-4/reddit-thread-hierarchy.svg", alt: "Constructed Reddit-style example: r/learnpython contains three threads. One selected thread expands into a post, comments, and indented replies.", caption: "Constructed Reddit-style teaching example · not a captured user conversation" },
      notes: "Use the community, selected thread, and nested reply boundaries to ask what counts as one document. A thread-level document contains the post and its ordered comment tree; a comment-level document needs both thread-family identity and reply targets. These self-written messages illustrate the hierarchy, not an acquired Reddit dataset or permission to train on real posts.",
      source: { label: "Reddit Help · community structure; constructed conversation", url: "https://support.reddithelp.com/hc/en-us/articles/204533569-What-are-communities-or-subreddits" },
    },
    {
      title: "Document length is not context length",
      textAnchor: "document-length-and-sequences",
      section: "1.1 The document unit is a modeling decision",
      kind: "comparison",
      headers: ["Corpus documents", "Later sequence construction"],
      rows: [["20-token definition", "Pack with explicit boundaries"], ["10,000-token chapter", "Split into context-sized windows"], ["Mixed document lengths", "Audit document and token exposure"]],
      notes: "Short and long coherent documents can coexist; do not add filler or destructively concatenate them to make a uniform corpus. A later builder can pack or window them for a 2,048-token context while retaining IDs, offsets, boundary tokens, and the attention policy.",
      source: { label: "Constructed lengths · not target distribution weights" },
    },
    {
      title: "Preserve structure before flattening",
      textAnchor: "preserve-document-structure",
      section: "1.2 Preserve structure before flattening",
      kind: "code",
      code: "document_id: doc-001\nparent_object_id: sha256:...\nextractor: html-maintext-v2\nblocks:\n  heading: Newton's second law\n  paragraph: The net force...\n  equation: F = ma\ntext_version: extracted-v1",
      notes: "The prose can remain fluent after the equation disappears, which is why a single text field is an insufficient extraction audit. Retain block identity and source locators before choosing the training serialization.",
      source: example,
    },
    {
      title: "An equation ID must resolve to the equation",
      textAnchor: "formula-reference-example",
      section: "1.2 Preserve structure before flattening",
      kind: "specimen",
      specimens: [
        { label: "Preserved", text: "p-7 → eq-1 + table-4\n\neq-1: F = ma\ntable-4: m = 2 kg\n         a = 3 m/s²\n\nResolved: F = 6 N" },
        { label: "Broken", text: "Using Eq. (1) and Table 4,\ncompute the force.\n\n[Equation missing]\n[Table missing]" },
      ],
      notes: "Keep scoped reference IDs and the actual equation/table blocks, including units. Resolve cross-document references using source identity where possible, and include self-contained content in training serialization; the student model does not automatically fetch a formula from an arbitrary ID.",
      source: example,
    },
    {
      title: "Store the score and the decision",
      textAnchor: "evidence-and-policy",
      section: "1.3 Separate evidence from policy",
      kind: "comparison",
      headers: ["Evidence", "Policy result"],
      rows: [["Language score: 0.94", "Accepted / rejected / review"], ["Repeated-line ratio: 0.02", "Threshold and rule ID"], ["Quality-model score: 0.73", "Policy version"]],
      notes: "A score is a measurement made by a particular procedure; acceptance is a policy applied to that evidence. Keeping both permits a later policy revision without reacquiring the page or necessarily rerunning expensive scoring.",
      source: example,
    },
    {
      title: "Retry the affected evidence—not every rejection",
      textAnchor: "toloka-selective-retry",
      section: "1.3 Separate evidence from policy",
      kind: "flow",
      items: ["Stored reasons + audio", "ASR-mismatch subset", "New model + new WER", "Reapply admission policy"],
      notes: "This is an illustrative extension, not a retry ledger claimed to exist in the released Toloka recipe. Rescore retained recordings rejected because of ASR mismatch when the recognizer improves; missing permission and irrecoverable corruption do not become eligible through that change, and old evidence remains versioned.",
      source: { label: "Illustrative selective-retry design · Lecture 4" },
    },
    {
      title: "One page: menus, prose, and a formula",
      textAnchor: "html-baseline-input",
      section: "2.2 A minimal DOM baseline",
      kind: "code",
      code: '<body>\n  <nav>Home | Physics | Contact</nav>\n  <main>\n    <h1>Newton\'s second law</h1>\n    <p>For constant mass, force equals mass times acceleration.</p>\n    <div class="equation">F = ma</div>\n  </main>\n  <footer>Privacy | Newsletter</footer>\n</body>',
      notes: "Start with this concrete HTML fixture and identify the intended content: the heading, paragraph, and equation inside main. Menus and the footer are outside the document. The next slide shows the baseline; predict what its selected tag list will miss before viewing the actual output.",
      source: example,
    },
    {
      title: "One baseline, inspectable failures",
      textAnchor: "dom-baseline-code",
      section: "2.2 A minimal DOM baseline",
      kind: "code",
      code: "DROP = {\"script\", \"style\", \"noscript\", \"nav\", \"footer\", \"form\"}\nsoup = BeautifulSoup(html, \"html.parser\")\nfor tag in soup.find_all(DROP):\n    tag.decompose()\n\nfor node in soup.find_all([\"h1\", \"h2\", \"h3\", \"p\", \"pre\", \"li\"]):\n    text = \" \".join(node.stripped_strings)\n    # append a block using node.name → type",
      notes: "Run this core of the chapter's baseline on the HTML shown immediately before it. DROP contains nav and footer; the selected-node list includes h1 and p but not div, so the formula disappears. Other chapter fixtures expose duplicate nested blocks and damaged highlighted-code whitespace.",
      source,
    },
    {
      title: "The tags chosen by the code decide what survives",
      textAnchor: "dom-failure-fixtures",
      section: "2.2 A minimal DOM baseline",
      kind: "specimen",
      specimens: [
        { label: "Required document", text: "[heading] Newton's second law\n\n[paragraph]\nFor constant mass, force equals\nmass times acceleration.\n\n[equation] F = ma" },
        { label: "Actual baseline output", text: "[heading] Newton's second law\n\n[paragraph]\nFor constant mass, force equals\nmass times acceleration." },
      ],
      items: ["Equation missing: div not selected"],
      notes: "Compare the output with the required document for the same HTML fixture. The baseline removes the site navigation and footer but loses meaningful content inside a div. Merely adding every div is not a complete repair: choose the main root and a nonoverlapping traversal, then test equations and nested containers explicitly.",
      source: example,
    },
    {
      title: "Highlighted code exposes the whitespace bug",
      textAnchor: "dom-failure-fixtures",
      section: "2.2 A minimal DOM baseline",
      kind: "specimen",
      specimens: [
        { label: "Plain pre: one text node", text: "<pre>if ready:\n    run()</pre>\n\nOutput:\nif ready:\n    run()" },
        { label: "Highlighted pre: multiple text nodes", text: "<pre><code>if ready:\n    <span>run()</span>\n</code></pre>\n\nOutput:\nif ready: run()" },
      ],
      notes: "A plain preformatted text node keeps internal indentation under this baseline, so it is a misleading test of the bug. Syntax highlighting introduces child nodes; stripped_strings removes their edge whitespace and the join destroys the intended code structure.",
      source: example,
    },
    {
      title: "Correct characters, wrong document",
      textAnchor: "pdf-reading-order",
      section: "3.1 PDFs: characters can be correct while the document is wrong",
      kind: "code",
      code: "Intended:        Extracted:\ncolumn 1, line 1 column 1, line 1\ncolumn 1, line 2 column 2, line 1\ncolumn 2, line 1 column 1, line 2\ncolumn 2, line 2 column 2, line 2\n\nSame characters. Different reading order.",
      notes: "A character-overlap score can miss a catastrophic reading-order failure in a two-column page. Equations, superscripts, minus signs, and table relationships also deserve explicit preservation fixtures.",
      source: example,
    },
    {
      title: "Two columns: complete the left before the right",
      textAnchor: "pdf-column-order-example",
      section: "3.1 PDFs: characters can be correct while the document is wrong",
      kind: "specimen",
      specimens: [
        { label: "Positioned page blocks", text: "LEFT                 RIGHT\n(y=100)              (y=100)\nForce depends        Example:\non mass.             m = 2 kg.\n\n(y=140)              (y=140)\nFor constant mass,   With a = 3 m/s²,\nF = ma.              F = 6 N." },
        { label: "Ordered document", text: "1. Force depends on mass.\n2. For constant mass, F = ma.\n3. Example: m = 2 kg.\n4. With a = 3 m/s², F = 6 N.\n\nKeep page + bounding boxes." },
      ],
      notes: "Show the spatial relationship before the serialized output. Top-to-bottom ordering can alternate columns; the explicit inspected-layout policy completes the left column first. The fixture is not a promise that a fixed midpoint or sort=True works on arbitrary scientific PDFs.",
      source: pdfDocs,
    },
    {
      title: "OCR can change the physics",
      textAnchor: "ocr-error-specimens",
      section: "3.1 PDFs: characters can be correct while the document is wrong",
      kind: "specimen",
      specimens: [
        { label: "Printed page", text: "F = ma\nm = 0.5 kg\na = −3 m/s²\nF = −1.5 N" },
        { label: "Possible OCR corruption", text: "F = rna\nm = O.5 kg\na = 3 m/s2\nF = 1.5 N" },
      ],
      items: ["m → rn · 0 → O", "Minus signs lost · superscript flattened"],
      notes: "These deliberately corrupted strings are a constructed fixture, not measured output from a particular OCR engine. Ask the class to locate the changed symbols and explain the consequences: a letter can become two letters, a digit can become a letter, a sign can vanish, and a superscript can become a baseline digit. Audit meaning-bearing structure, not only ordinary word accuracy.",
      source: example,
    },
    {
      title: "Code and rows need their own paths",
      textAnchor: "code-and-repositories",
      section: "3. Extraction for PDFs, code, and structured datasets",
      kind: "comparison",
      headers: ["Code repository", "Structured dataset"],
      rows: [["Commit + file path", "Dataset revision + row ID"], ["Preserve indentation", "Map question / solution fields"], ["Record vendor/generated flags", "Preserve parent and family IDs"], ["Keep file boundaries", "Version the mapping"]],
      notes: "Do not send a structured row through a fictional HTML extraction step. Standardize the resulting contract while keeping the evidence and representation-specific requirements of each source type.",
      source,
    },
    {
      title: "Define the reference before the score",
      textAnchor: "extraction-reference-guidelines",
      section: "4.1 Write extraction guidelines first",
      kind: "points",
      items: ["Required blocks and reading order", "Titles, captions, comments, references", "Equations, tables, and code", "Documented block-alignment rule"],
      notes: "Two annotators can disagree because the extraction policy never specified whether captions or comments belong. Resolve the rubric before interpreting a difference as an extractor error.",
      source,
    },
    {
      title: "Parentheses: what was the reader meant to say?",
      textAnchor: "parenthetical-reading-guidelines",
      section: "4.1 Write extraction guidelines first",
      kind: "reading",
      readingText: "Երևանում (Հայաստանի մայրաքաղաքում) բացվեց նոր գիտական կենտրոն։",
      notes: "In the Armenian Toloka collection, parentheses were not explicitly covered by the reading instructions, and some readers skipped the parenthetical words. This constructed sentence illustrates the issue; it is not a recovered recording. If an ASR model perfectly transcribes the short reading, comparison with the seven-word full reference still gives two deletions and 28.6% WER. Specify the intended speech before collection and review existing ambiguous cases without automatically treating omission as misconduct.",
      source: { label: "Toloka collection experience · constructed sentence and WER" },
    },
    {
      title: "Precision keeps junk visible; recall finds loss",
      textAnchor: "extraction-precision-and-recall",
      section: "4.2 Block-level precision and recall",
      kind: "formula",
      formula: "precision = correct retained / all retained\nrecall = correct retained / all required",
      notes: "The unit here is an aligned block occurrence, not a set of distinct word types. A vocabulary set could hide both paragraph duplication and omission, while the block contract makes those failures count.",
      source,
    },
    {
      title: "Good extraction keeps content—not the menu",
      textAnchor: "extraction-reference-specimens",
      section: "4.2 Block-level precision and recall",
      kind: "specimen",
      specimens: [
        { label: "Good · precision 1.00 / recall 1.00", text: "A  Newton's second law\nB  For constant mass, force equals\n   mass times acceleration.\nC  F = ma\nD  force = mass * acceleration" },
        { label: "Bad · precision 0.75 / recall 0.75", text: "N  Home | Physics | Contact\nA  Newton's second law\nB  For constant mass, force equals\n   mass times acceleration.\nD  force = mass * acceleration" },
      ],
      items: ["Reference: heading, paragraph, equation, code", "Bad output: menu added; equation missing", "Removing the menu alone leaves recall 0.75"],
      notes: "The fixture has four required block occurrences, A through D; the source menu N is outside the reference. The good output returns four correct blocks. The bad output returns three correct blocks and one unwanted menu, so both precision and recall are 3/4. Deleting the menu raises precision to 1 but cannot restore the missing equation; score order separately even when both selection metrics are perfect.",
      source: example,
    },
    {
      title: "The average hides the missing equation",
      textAnchor: "extractor-comparison-example",
      section: "4.3 Worked example",
      kind: "table",
      headers: ["Measure", "Extractor A", "Extractor B"],
      rows: [["Correct / returned blocks", "9 / 10", "10 / 10"], ["Required blocks", "11", "11"], ["Precision / recall", "0.90 / 0.818", "1.00 / 0.909"], ["Equation + code retained", "Neither", "Both"]],
      notes: "A returns every paragraph but loses the equation and code; B misses one paragraph but keeps both technical blocks. The aggregate score helps, but block-type preservation explains which failure matters for a technical corpus.",
      source: example,
    },
    {
      title: "Compare on the same source objects",
      textAnchor: "paired-extractor-comparisons",
      section: "4.5 Paired extractor comparisons",
      kind: "flow",
      items: ["Frozen objects", "Run A and B", "Align to reference", "Inspect disagreements"],
      notes: "Paired processing removes differences in source difficulty from the extractor comparison. Inspect article pages, documentation, short pages, and tables separately before choosing a winner from a global average.",
      source,
    },
    {
      title: "Same word, new encoding—or new wording?",
      textAnchor: "normalization-policy-examples",
      section: "5.2 Canonical versus compatibility normalization",
      kind: "specimen",
      specimens: [
        { label: "Unicode NFC · same word", text: "cafe\u0301  →  café\n\nLast letter:\nU+0065 U+0301  →  U+00E9\n  e    +  ◌́   →     é" },
        { label: "Armenian speech policy · new wording", text: "12  →  տասներկու\n\n12 կգ  →  տասներկու կիլոգրամ\n\nNot a Unicode operation." },
      ],
      items: ["Choose the policy for the task and block type"],
      notes: "NFC composes canonically equivalent code points, so the apparent word can stay unchanged while its encoding changes. Spelling out a number and expanding a unit for Armenian speech is a separate, task-specific text policy; do not apply it blindly to dates, identifiers, code, or equations. Formal Unicode normalization has defined forms even when a project's broader rewriting policy varies.",
      source: { label: "Unicode UAX #15 · constructed encoding and Armenian speech examples", url: "https://unicode.org/reports/tr15/" },
    },
    {
      title: "A rerun should not keep changing the text",
      textAnchor: "idempotence-pass-example",
      section: "5.3 Idempotence",
      kind: "specimen",
      specimens: [
        { label: "Idempotent · collapse each space run", text: 're.sub(r" +", " ", text)\n\ninput    a····b\npass 1   a·b\npass 2   a·b' },
        { label: "Not idempotent · replace pairs once", text: 'text.replace("  ", " ")\n\ninput    a····b\npass 1   a··b\npass 2   a·b' },
      ],
      items: ["Stable output makes reruns reproducible"],
      notes: "Each dot represents one ordinary space in this prose-only example. Replacing each full run of spaces stabilizes after one pass, while nonoverlapping pair replacement can keep changing the result on a rerun. Prefer a stable transformation when rebuilding; the next slide shows why this property alone says nothing about preservation, and neither whitespace rule is suitable for arbitrary Python code.",
      source: { label: "Constructed example · · represents one space" },
    },
    {
      title: "Can a destructive normalizer be idempotent?",
      textAnchor: "idempotence-not-correctness",
      section: "5.3 Idempotence",
      kind: "question",
      prompt: "N(N(x)) = N(x) passes for every input.\nIs that enough to call N safe?",
      answer: "No. Returning an empty string also passes.",
      answerCode: 'def normalize(text):\n    return ""',
      notes: "Use this pause to separate an algebraic invariant from preservation of useful information. The test suite needs multilingual prose, code, equations, and offsets in addition to an idempotence assertion.",
      source: example,
    },
    {
      title: "Same page, different label vocabularies",
      textAnchor: "language-evidence-sources",
      section: "6.1 Keep label sources separate",
      kind: "specimen",
      specimens: [
        { label: "Stored language evidence", text: '{\n  "publisher_language": "hy",\n  "html_lang_attribute": "hy",\n  "lid_model": "glotlid-revision-X",\n  "lid_prediction": "hye_Armn",\n  "lid_score": 0.94,\n  "human_audit_label": null\n}' },
        { label: "Project-defined audit labels", text: "mostly_hy\nmostly_en\nmixed_hy_en\nunknown\ninsufficient_text" },
      ],
      items: ["hy: source declaration · hye_Armn: model language–script tag", "null: not audited · unknown: audited, unresolved"],
      notes: "The source declaration, model label vocabulary, and project audit rubric are different kinds of evidence. The model revision and score are illustrative, not a measured run. The proposed project labels accommodate mixed and insufficient-text cases; reserve null for missing audit evidence, and do not treat a maximum model score as a calibrated probability of correctness.",
      source,
    },
    {
      title: "Rare languages expose the base-rate trap",
      textAnchor: "language-base-rate-example",
      section: "6.4 Worked example: the base-rate problem",
      kind: "specimen",
      specimens: [
        { label: "100 target-language pages", text: "0.1% of 100,000 pages\n\n90% correctly flagged\n→ 90 correct flags\n→ 10 missed" },
        { label: "99,900 other-language pages", text: "99.9% of 100,000 pages\n\n1% incorrectly flagged\n→ 999 wrong flags\n→ 98,901 correctly rejected" },
      ],
      items: ["Selected: 90 correct + 999 wrong = 1,089 pages", "Precision: 90 / 1,089 ≈ 8.3%", "A small error rate acts on a much larger population"],
      notes: "Count documents before applying Bayes' rule. The 90% true-positive rate recovers 90 of the 100 target pages, while a 1% false-positive rate contributes 999 pages from the much larger other-language group. Only 90 of the 1,089 selected pages are target-language; these are constructed rates and prevalence, not a measured result for Armenian or a particular LID model.",
      source: example,
    },
    {
      title: "Mixed-language does not mean unusable",
      textAnchor: "mixed-language-documents",
      section: "6.5 Mixed-language documents",
      kind: "points",
      items: ["Explanation in one language", "Citations and identifiers in another", "Equations with no language label", "Block-level evidence where needed"],
      notes: "An Armenian programming tutorial is one example of a broader multilingual pattern. A dominant-language label may hide useful switching, so label mixed and insufficient-text cases explicitly rather than forcing every block into one language.",
      source,
    },
    {
      title: "Which property is called quality?",
      textAnchor: "quality-label-axes",
      section: "7.1 Separate possible label axes",
      kind: "table",
      headers: ["Axis", "Question"],
      rows: [["Extraction integrity", "Did the intended document survive?"], ["Language evidence", "Is the intended language present?"], ["Substantive content", "More than menus and templates?"], ["Technical structure", "Are formulas and code intact?"]],
      notes: "These axes can disagree without contradiction. A useful code tutorial may score poorly under a prose-style classifier, and an impeccably extracted page can still be factually wrong.",
      source,
    },
    {
      title: "A feature is not its interpretation",
      textAnchor: "heuristic-quality-signals",
      section: "7.2 Heuristic quality signals",
      kind: "comparison",
      headers: ["Observed signal", "Competing explanations"],
      rows: [["Low alphabetic ratio", "Corruption / equations / code"], ["Repeated lines", "Boilerplate / reference table"], ["Short document", "Empty page / complete definition"], ["Few sentence endings", "Bad prose / list or documentation"]],
      notes: "Heuristics are useful precisely because students can inspect what they measure. The error is promoting a cheap surface feature into a universal judgment without language- and source-specific validation.",
      source,
    },
    {
      title: "Surprisal measures familiarity, not value",
      textAnchor: "language-model-quality-scores",
      section: "7.4 Language-model-based scores",
      kind: "formula",
      formula: "Hq(x) = −(1/m) Σₜ log q(xₜ | x<ₜ)\nhigh loss: unfamiliar or corrupted\nlow loss: familiar or repetitive",
      notes: "A scorer with little exposure to a technical language can reject exactly the missing coverage a project wants. Pin the scorer and tokenizer, and interpret the score relative to their distribution rather than as intrinsic document value.",
      source,
    },
    {
      title: "Label first. Tune second. Audit last.",
      textAnchor: "quality-audit-workflow",
      section: "8. Build the audit labels before selecting the threshold",
      kind: "flow",
      items: ["Define rubric", "Sample population", "Annotate blind", "Resolve ambiguity", "Tune on dev", "Held-out audit"],
      notes: "Hide filter decisions from annotators when practical and preserve individual judgments after adjudication. Keep source families together when the intended test is generalization to unseen sources rather than familiar templates.",
      source,
    },
    {
      title: "A clean accepted sample proves recall?",
      textAnchor: "precision-recall-question",
      section: "9. Evaluate both retained and rejected material",
      kind: "question",
      prompt: "95 of 100 sampled retained documents are good.\nWhat has the audit estimated?",
      answer: "About 95% of the kept documents look good. We still do not know how many good documents were discarded.",
      notes: "A representative retained-only audit estimates how clean the kept set is, not how much useful material survived. Ask where the evidence about discarded good documents would come from; the next fully labeled toy example makes the two denominators visible.",
      source: example,
    },
    {
      title: "95% clean does not mean 95% recovered",
      textAnchor: "precision-recall-readable-example",
      section: "9. Evaluate both retained and rejected material",
      kind: "specimen",
      specimens: [
        { label: "Kept · 100 pages", text: "95 good pages\n 5 junk pages" },
        { label: "Discarded · 900 pages", text: "405 good pages\n495 junk pages" },
      ],
      items: ["Start: 1,000 pages, including 500 good pages", "Precision: 95 of 100 kept pages are good → 95%", "Recall: only 95 of 500 good pages were kept → 19%"],
      notes: "These exact counts describe a constructed fully labeled pool, not estimates inferred from the preceding retained-only sample. The kept set looks clean: 95 of its 100 pages are good. But the filter discarded another 405 good pages, leaving only 95 of the original 500 good pages; an accepted-only audit cannot reveal those losses.",
      source: example,
    },
    {
      title: "Audit the rejected population too",
      textAnchor: "retained-rejected-audit-example",
      section: "9.1 Worked example: accepted and rejected audits",
      kind: "table",
      headers: ["Partition", "Population", "Audit good", "Estimated good"],
      rows: [["Retained", "6,000", "180 / 200", "5,400"], ["Rejected", "4,000", "40 / 200", "800"]],
      notes: "The audit samples equally from unequal partitions. Expand each within-partition good rate by its population size before estimating corpus totals or recall.",
      source: example,
    },
    {
      title: "Choose a policy, not a magic number",
      textAnchor: "threshold-decision",
      section: "10. Threshold selection is a decision under constraints",
      kind: "points",
      items: ["Define minimum retained precision", "Preserve the target coverage", "Respect non-negotiable exclusions", "Select on development evidence", "Report held-out uncertainty"],
      notes: "The chapter proposes maximizing retained scientific coverage subject to a precision constraint. Make the objective and the uncertainty explicit; a threshold selected on repeated inspection of final audit data no longer has an untouched evaluation.",
      source,
    },
    {
      title: "One threshold can mean different things",
      textAnchor: "language-specific-thresholds",
      section: "10.2 Per-language thresholds can be justified",
      kind: "points",
      items: ["Calibration differs by language", "Length and punctuation differ", "Training labels differ in coverage", "Validate each operating point"],
      notes: "FineWeb2 supplies a concrete multilingual example of adapting filtering to languages and scripts. Per-language thresholds are not automatically correct; they require a shared objective and validation of each resulting trade-off.",
      source: { label: "FineWeb2 · Penedo et al. 2025", url: "https://arxiv.org/abs/2506.20920" },
    },
    {
      title: "Document retention by source",
      textAnchor: "source-retention-example",
      section: "11.1 Before/after composition for the running example",
      kind: "bars",
      bars: [{ label: "Natural web/news", value: 85 }, { label: "Education/science", value: 60 }, { label: "Translated STEM", value: 95 }],
      unit: "%",
      notes: "These are the chapter's constructed document-retention rates for its illustrative Armenian case. The 40 percent loss of education/science deserves investigation into extraction, formulas, LID, and classifier style—not an automatic conclusion that those sources were worse.",
      source: example,
    },
    {
      title: "Good stage rates can leave little data",
      textAnchor: "conditional-cumulative-retention",
      section: "11.2 Conditional versus cumulative retention",
      kind: "formula",
      formula: "90% extraction × 85% language × 75% quality\n= 57.375% cumulative retention",
      notes: "The second rate is conditional on passing extraction, and the third on passing both preceding stages. Multiplication follows the conditional chain rule; it does not assume independent filters.",
      source: example,
    },
    {
      title: "A document and a token sample differ",
      textAnchor: "document-token-weighting",
      section: "11.3 Document-weighted versus token-weighted feature rates",
      kind: "table",
      headers: ["Quantity", "Example"],
      rows: [["Document A", "10 occurrences / 100 tokens"], ["Document B", "0 occurrences / 900 tokens"], ["Mean document rate", "(0.10 + 0) / 2 = 5%"], ["Corpus token rate", "10 / 1,000 = 1%"]],
      notes: "Neither number is an error: one samples documents uniformly and the other samples token positions uniformly. Match the denominator to the claim and name the weighting in every before/after report.",
      source: example,
    },
    {
      title: "The same count can mean one source",
      textAnchor: "frequency-and-dispersion",
      section: "11.5 Frequency and dispersion",
      kind: "points",
      items: ["Count occurrences", "Count documents with the feature", "Count independent source families", "Inspect contexts behind the spike"],
      notes: "A phrase on a hundred pages from one mirrored site can appear widespread while providing little independent source coverage. Dispersion depends on the partition, so a document-level statistic and a source-family statistic answer different questions.",
      source,
    },
    {
      title: "Finding a bug is not measuring its rate",
      textAnchor: "exploration-and-prevalence",
      section: "12.3 Exploration and prevalence estimation are different",
      kind: "comparison",
      headers: ["Exploratory inspection", "Probability audit"],
      rows: [["Search suspicious strings", "Sample a defined population"], ["Inspect borderline cases", "Keep inclusion weights"], ["Discover a failure mechanism", "Estimate prevalence + uncertainty"]],
      notes: "Searching rejected text for F = ma can reveal wrongly rejected physics pages. It cannot estimate the corpus-wide error rate without a probability sample from the relevant rejected population.",
      source,
    },
    {
      title: "Reject obvious failures before costly scoring",
      textAnchor: "filter-order-cost",
      section: "14.1 Cheap filters before expensive filters",
      kind: "specimen",
      specimens: [
        { label: "Structural check first · 1 unit per page", text: "Check 100 pages: 100 units\n30 fail → stop\n\nScore 70 survivors: 1,400 units\n\nTotal: 1,500 units" },
        { label: "Neural scorer first · 20 units per page", text: "Score 100 pages: 2,000 units\n40 fail → stop\n\nCheck 60 survivors: 60 units\n\nTotal: 2,060 units" },
      ],
      items: ["Structural check: empty or corrupted pages", "Neural scorer: model-based quality judgment", "Cheap first avoids scoring 30 rejected pages"],
      notes: "Both fixed rules inspect the same unchanged input, and rejection stops further work. The structural check costs one unit and passes 70 of the 100 starting pages; the neural scorer costs twenty units and passes 60 when run first. Cheap-first skips expensive scoring on 30 pages, saving 560 units overall without changing the final intersection. These are constructed costs; measure actual costs and pass rates, and reassess if stages rewrite text.",
      source: example,
    },
    {
      title: "A transformation can change the decision",
      textAnchor: "transformation-order",
      section: "14.2 Some transformations do not commute",
      kind: "comparison",
      headers: ["Fixed predicates", "Changing representations"],
      rows: [["Same immutable input", "Normalization rewrites input"], ["Final intersection can agree", "LID can change after rewriting"], ["Order mainly changes cost", "Order can change membership"]],
      notes: "A pipeline is not just a list of Boolean functions when stages mutate the text. Keep intermediate representations and transformation versions so a change in acceptance can be traced to the actual intervention.",
      source,
    },
    {
      title: "Return to the missing physics page",
      textAnchor: "document-processing-trace",
      section: "15. End-to-end worked trace for one document",
      kind: "flow",
      items: ["Archived page", "Equation preserved", "Mostly-target LID", "Quality score 0.66", "Audit: useful", "Test policy revision"],
      notes: "The chapter's page fails a hypothetical global threshold of 0.70 despite a sound extraction. One false negative motivates a hypothesis and a probability audit; it does not by itself justify a new global policy.",
      source: example,
    },
    {
      title: "Does cleaner imply a better model?",
      textAnchor: "corpus-model-evidence",
      section: "Deliverable",
      kind: "question",
      prompt: "The new corpus passes every stated audit.\nHas downstream model improvement been established?",
      answer: "No. That claim needs a controlled training experiment.",
      notes: "Corpus audits verify the defined processing contract and reveal risks, but do not replace model-level evidence. Use this final pause to connect measured document properties to the later training experiment without promising an unmeasured gain.",
      source,
    },
    {
      title: "An auditable document, not just clean text",
      textAnchor: "lecture-takeaways",
      section: "What to remember",
      kind: "points",
      items: ["Preserve structure and ancestry", "Name every measured property", "Audit both sides of each decision", "Measure who disappeared", "Version the evidence and policy"],
      notes: "Close by asking students to trace one processing decision back to its stored evidence and policy. Use discussion to consolidate extraction, language evidence, and the two sides of a filter; keep the extended checkpoint, keyness, and full dispersion derivations as optional reading.",
      source,
    },
  ],
};

export default deck;
